on:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install Dependencies
        run: bun install

      - name: 🚀 Create Build
        run: eas build -p ios --profile production --non-interactive --auto-submit --no-wait

      - name: 👨‍💻 Commit & Push changes
        run: |
          git config --global user.name 'Jon Stuebe'
          git config --global user.email 'jonstuebe@users.noreply.github.com'
          git add .
          git commit -m "chore: bumped build version"
          git push
